import {StyleSheet} from 'react-native';

export default StyleSheet.create({

	Container:{
		flex:1,
		backgroundColor:'white'

	},
	UpperSection:{
		flex:2,
		backgroundColor:'orange'
	},
	LowerSection:{
		flex:1,
		marginTop:10
	},
	CompanyLogoSection:{
		flex:2,
		flexDirection:'column',
		alignItems:'center',
		justifyContent:'center'
	},
	AppLogoSection:{
		flex:2,
		flexDirection:'column',
		alignItems:'center',
		justifyContent:'center'
	},
	AppNameSection:{
		flex:1,
		flexDirection:'row',
		alignItems:'flex-start',
		justifyContent:'center'
	},
	AppLogo:{
		height:150,
		width:150
	},
	CompanyLogo:{
		height:100,
		width:310
	},
	AppName:{
		fontSize:20,
		fontWeight:'bold',
		marginTop:10,
		color:'white'
	},
	UsernameSection:{
		flex:1,
		alignItems:'center',
		justifyContent:'flex-start'
	},
	PasswordSection:{
		flex:1,
		alignItems:'center',
		justifyContent:'flex-start'	
	},
	LoginButtonSection:{
		flex:2,
		alignItems:'center',
		justifyContent:'flex-start'
	},
	TextInput:{
		height:30,
		width:300,
		borderBottomColor:'red',
		borderBottomWidth:1,
		backgroundColor:'white',marginTop:10,
	},
	LoginButtonStyle:{
		alignSelf:'stretch',
		backgroundColor:'#50AE54',
		marginTop:10,
		marginLeft:50,
		marginRight:50,
		height:40,
		borderRadius:5,
		borderColor:'#50AE54',
		borderWidth:1,
		alignItems:'center',
		justifyContent:'center'
	},
	ButtonTextStyle:{
		fontSize:20,
		fontWeight:'600',
		color:'white'					
	}

})